# Sample ordering

Order the samples in the training datasets.

## Setup

In [1]:
import pandas as pd
import numpy as np

In [2]:
# read in prepared dataset from previous step
df = pd.read_pickle("data/interim/3_outliers_flagged.pkl")
wavelength_cols = df.filter(regex="^\d+", axis=1).columns.tolist()
descriptive_cols = [col for col in df.columns if col not in wavelength_cols]
df

,partition_1,outlier_flag_1,train_partition_1,partition_ext,origin,population,date,season,region,cultivar,...,1173,1176,1179,1182,1185,1188,1191,1194,1197,1200
0,train,0,calibration,train,published,100100,2015-09-27,2015,NT,caly,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,train,0,calibration,train,published,100100,2015-09-27,2015,NT,caly,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,train,0,calibration,train,published,100100,2015-09-27,2015,NT,caly,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,train,0,calibration,train,published,100100,2015-09-27,2015,NT,caly,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,train,0,calibration,train,published,100100,2015-09-27,2015,NT,caly,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85396,holdout,0,calibration,train,marcelo,200800,NaT,2021,QLD,keitt,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
85397,holdout,0,calibration,train,marcelo,200800,NaT,2021,QLD,keitt,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
85398,holdout,0,calibration,train,marcelo,200800,NaT,2021,QLD,keitt,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
85399,holdout,0,calibration,train,marcelo,200800,NaT,2021,QLD,keitt,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
85400,holdout,0,calibration,train,marcelo,200800,NaT,2021,QLD,keitt,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Create Sample Orderings

In [3]:
# random sample order
np.random.seed(42)
df.insert(
    loc=3, 
    column="sample_order_1", 
    value=np.random.permutation(len(df))
)

In [4]:
df

,partition_1,outlier_flag_1,train_partition_1,sample_order_1,partition_ext,origin,population,date,season,region,...,1173,1176,1179,1182,1185,1188,1191,1194,1197,1200
0,train,0,calibration,28262,train,published,100100,2015-09-27,2015,NT,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,train,0,calibration,80895,train,published,100100,2015-09-27,2015,NT,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,train,0,calibration,31015,train,published,100100,2015-09-27,2015,NT,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,train,0,calibration,563,train,published,100100,2015-09-27,2015,NT,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,train,0,calibration,3737,train,published,100100,2015-09-27,2015,NT,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85396,holdout,0,calibration,6265,train,marcelo,200800,NaT,2021,QLD,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
85397,holdout,0,calibration,54886,train,marcelo,200800,NaT,2021,QLD,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
85398,holdout,0,calibration,76820,train,marcelo,200800,NaT,2021,QLD,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
85399,holdout,0,calibration,860,train,marcelo,200800,NaT,2021,QLD,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
85400,holdout,0,calibration,15795,train,marcelo,200800,NaT,2021,QLD,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Output data

In [5]:
# output
df.to_pickle("data/interim/4_sample_order.pkl")